import Script from "next/script";
import "./globals.css";
import CommonLayout from "@/src/layout/Common";

export const metadata = {
  // title: "Conscious Namaz",
  // description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Set the favicon path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script
        type="text/javascript"
        src="https://checkout.razorpay.com/v1/checkout.js"
      />
      <body className={`pt-[--header-height] antialiased`}>
        <CommonLayout>{children}</CommonLayout>
      </body>
    </html>
  );
}
